spring:
application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: anjubaoykq
    url: jdbc:mysql://172.16.33.1:3306/testcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
server:
  port: 8763
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
